/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import business.Cashier;
import data.CashierDB;
import javax.swing.JOptionPane;

/**
 *
 * @author chand
 */
public class CashierLoginUI extends javax.swing.JFrame {
    
    private CashierDB cashierdb;

    /**
     * Creates new form CashierLoginUI
     */
    public CashierLoginUI() {
        initComponents();
        setLocationRelativeTo(this);
        cashierdb = new CashierDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCashierLogin = new javax.swing.JLabel();
        lblCashierUsername = new javax.swing.JLabel();
        lblCashierPassword = new javax.swing.JLabel();
        txtCashierUsername = new javax.swing.JTextField();
        pswCashierPassword = new javax.swing.JPasswordField();
        btnCashierLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuitemBacktoHome = new javax.swing.JMenuItem();
        mnuManager = new javax.swing.JMenu();
        mnuitemManagerCockpit = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();
        mnuitemClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier Login");
        setResizable(false);

        lblCashierLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCashierLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashierLogin.setText("Cashier Login");

        lblCashierUsername.setText("Username");

        lblCashierPassword.setText("Password");

        btnCashierLogin.setText("Login");
        btnCashierLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierLoginActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCashierLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCashierUsername)
                    .addComponent(pswCashierPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCashierLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCashierLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCashierLogin)
                    .addComponent(btnBack))
                .addGap(30, 30, 30))
        );

        mnuHome.setText("iStore");

        mnuitemBacktoHome.setText("Home");
        mnuitemBacktoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemBacktoHomeActionPerformed(evt);
            }
        });
        mnuHome.add(mnuitemBacktoHome);

        jMenuBar1.add(mnuHome);

        mnuManager.setText("Manager");

        mnuitemManagerCockpit.setText("Manager Cockpit");
        mnuitemManagerCockpit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemManagerCockpitActionPerformed(evt);
            }
        });
        mnuManager.add(mnuitemManagerCockpit);

        jMenuBar1.add(mnuManager);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });

        mnuitemClose.setText("Close the Application");
        mnuitemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemCloseActionPerformed(evt);
            }
        });
        mnuExit.add(mnuitemClose);

        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitemManagerCockpitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemManagerCockpitActionPerformed
        // TODO add your handling code here:
        ManagerLoginUI managerloginui = new ManagerLoginUI();
        managerloginui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemManagerCockpitActionPerformed

    private void mnuitemBacktoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemBacktoHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemBacktoHomeActionPerformed

    private void mnuitemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitemCloseActionPerformed

    private void btnCashierLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierLoginActionPerformed
        // TODO add your handling code here:
        String cashierUsername = txtCashierUsername.getText();
        String cashierPassword = new String(pswCashierPassword.getPassword()); 
        Cashier cashier = cashierdb.get(cashierUsername);
    
        if (cashier != null && cashierPassword.equals(cashier.getCashierPassword())) {
            ProductUI productui = new ProductUI();
            productui.setVisible(true);
            setVisible(false);
        } else {
            String message = "Invalid Username or Password";
            JOptionPane.showMessageDialog(this, message); 
            
            txtCashierUsername.setText("");
            pswCashierPassword.setText("");
        }
    }//GEN-LAST:event_btnCashierLoginActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCashierLogin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCashierLogin;
    private javax.swing.JLabel lblCashierPassword;
    private javax.swing.JLabel lblCashierUsername;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenu mnuManager;
    private javax.swing.JMenuItem mnuitemBacktoHome;
    private javax.swing.JMenuItem mnuitemClose;
    private javax.swing.JMenuItem mnuitemManagerCockpit;
    private javax.swing.JPasswordField pswCashierPassword;
    private javax.swing.JTextField txtCashierUsername;
    // End of variables declaration//GEN-END:variables
}
