/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import javax.swing.JOptionPane;

/**
 *
 * @author chand
 */
public class ManagerLoginUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerLoginUI
     */
    public ManagerLoginUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblManagerLogin = new javax.swing.JLabel();
        lblManagerUsername = new javax.swing.JLabel();
        lblManagerPassword = new javax.swing.JLabel();
        txtManagerUsername = new javax.swing.JTextField();
        pswManagerPassword = new javax.swing.JPasswordField();
        btnManagerLogin = new javax.swing.JButton();
        btnManagerBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuitemHome = new javax.swing.JMenu();
        mnuitemiStoreHome = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuitemCashierLog = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuitemClosetheApplication = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Login");
        setResizable(false);

        lblManagerLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblManagerLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagerLogin.setText("Manager Login");

        lblManagerUsername.setText("Username");

        lblManagerPassword.setText("Password");

        btnManagerLogin.setText("Login");
        btnManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerLoginActionPerformed(evt);
            }
        });

        btnManagerBack.setText("Back");
        btnManagerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblManagerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblManagerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(lblManagerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtManagerUsername)
                            .addComponent(pswManagerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnManagerLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManagerBack)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManagerLogin)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManagerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagerLogin)
                    .addComponent(btnManagerBack))
                .addGap(23, 23, 23))
        );

        mnuitemHome.setText("iStore");
        mnuitemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemHomeActionPerformed(evt);
            }
        });

        mnuitemiStoreHome.setText("Home");
        mnuitemiStoreHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemiStoreHomeActionPerformed(evt);
            }
        });
        mnuitemHome.add(mnuitemiStoreHome);

        jMenuBar1.add(mnuitemHome);

        jMenu2.setText("Cashier");

        mnuitemCashierLog.setText("Cashier Login");
        mnuitemCashierLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemCashierLogActionPerformed(evt);
            }
        });
        jMenu2.add(mnuitemCashierLog);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exit");

        mnuitemClosetheApplication.setText("Close the Appliication");
        mnuitemClosetheApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemClosetheApplicationActionPerformed(evt);
            }
        });
        jMenu3.add(mnuitemClosetheApplication);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemHomeActionPerformed

    private void mnuitemCashierLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemCashierLogActionPerformed
        // TODO add your handling code here:
        CashierLoginUI cashierloginui = new CashierLoginUI();
        cashierloginui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemCashierLogActionPerformed

    private void mnuitemClosetheApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemClosetheApplicationActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitemClosetheApplicationActionPerformed

    private void btnManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerLoginActionPerformed
        // TODO add your handling code here:
        String managerUserID = txtManagerUsername.getText();
        String managerPassword = pswManagerPassword.getText();
        
        if (managerUserID.equals("admin") && managerPassword.equals("admin")) {
          ManagerCockpitUI managercockpitui = new ManagerCockpitUI()  ;
          managercockpitui.setVisible(true);
          setVisible(false);
        } else {
            String Message = "Invalid Username & Password";
            JOptionPane.showMessageDialog(this,Message);
            
            // Clear the text fields
            txtManagerUsername.setText("");
            pswManagerPassword.setText("");
        }
    }//GEN-LAST:event_btnManagerLoginActionPerformed

    private void mnuitemiStoreHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemiStoreHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemiStoreHomeActionPerformed

    private void btnManagerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerBackActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnManagerBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagerBack;
    private javax.swing.JButton btnManagerLogin;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblManagerLogin;
    private javax.swing.JLabel lblManagerPassword;
    private javax.swing.JLabel lblManagerUsername;
    private javax.swing.JMenuItem mnuitemCashierLog;
    private javax.swing.JMenuItem mnuitemClosetheApplication;
    private javax.swing.JMenu mnuitemHome;
    private javax.swing.JMenuItem mnuitemiStoreHome;
    private javax.swing.JPasswordField pswManagerPassword;
    private javax.swing.JTextField txtManagerUsername;
    // End of variables declaration//GEN-END:variables
}
