/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import business.Products;
import data.ProductDB;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chand
 */
public class ManageProductsUI extends javax.swing.JFrame {

    private ProductDB productsdb;
    private DefaultTableModel tblModel;
    
    /**
     * Creates new form ManageProductsUI
     */
    public ManageProductsUI() {
        initComponents();
        setLocationRelativeTo(this);
        productsdb = new ProductDB();
        tblModel = new DefaultTableModel();
        tblProducts.setModel(tblModel);
        tblModel.addColumn("Product ID");
        tblModel.addColumn("Category");
        tblModel.addColumn("Name");
        tblModel.addColumn("Price");
        tblModel.addColumn("Serila Number");
        tblModel.addColumn("Quantity");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblAddorEditProducts = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductSerialNumber = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtProductSerialNumber = new javax.swing.JTextField();
        lblProductCategory = new javax.swing.JLabel();
        cmbCategoty = new javax.swing.JComboBox<>();
        lblProductPrice = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        lblProductQuantity = new javax.swing.JLabel();
        txtProductQuantity = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnViewallProducts = new javax.swing.JButton();
        btnUpdateProducts = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuiStore = new javax.swing.JMenu();
        mnuitemHome = new javax.swing.JMenuItem();
        mnuServices = new javax.swing.JMenu();
        mnuitemManageCashierAccounts = new javax.swing.JMenuItem();
        mnuitemViewProducts = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();
        mnuitemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add / Edit Products");
        setResizable(false);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        lblAddorEditProducts.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAddorEditProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddorEditProducts.setText("Add / Edit Products");

        lblProductID.setText("Product ID");

        lblProductName.setText("Name");

        lblProductSerialNumber.setText("Serial Number");

        txtProductSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductSerialNumberActionPerformed(evt);
            }
        });

        lblProductCategory.setText("Category");

        cmbCategoty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mac", "iPad", "iPhone", "Watch", "AirPods", "Tv & Home", "Entertainment", "Accessories" }));

        lblProductPrice.setText("Price");

        lblProductQuantity.setText("Quantity");

        btnAddProduct.setText("Add");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnSearchProduct.setText("Search");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        btnViewallProducts.setText("View All");
        btnViewallProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewallProductsActionPerformed(evt);
            }
        });

        btnUpdateProducts.setText("Update");
        btnUpdateProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtProductSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAddProduct)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchProduct)
                                .addGap(35, 35, 35)
                                .addComponent(btnUpdateProducts)
                                .addGap(0, 45, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProductPrice)
                                    .addComponent(lblProductCategory)
                                    .addComponent(lblProductQuantity))
                                .addGap(153, 153, 153))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDeleteProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btnViewallProducts)
                                .addGap(55, 55, 55)))
                        .addComponent(btnBack)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductSerialNumber)
                            .addComponent(lblProductID)
                            .addComponent(lblProductName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProductPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategoty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddorEditProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAddorEditProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductID)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductCategory)
                    .addComponent(cmbCategoty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductPrice))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductQuantity)
                    .addComponent(txtProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnSearchProduct)
                    .addComponent(btnDeleteProduct)
                    .addComponent(btnViewallProducts)
                    .addComponent(btnUpdateProducts)
                    .addComponent(btnBack))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnuiStore.setText("iStore");

        mnuitemHome.setText("Home");
        mnuitemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemHomeActionPerformed(evt);
            }
        });
        mnuiStore.add(mnuitemHome);

        jMenuBar1.add(mnuiStore);

        mnuServices.setText("Services");

        mnuitemManageCashierAccounts.setText("Manage Cashier Accounts");
        mnuitemManageCashierAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemManageCashierAccountsActionPerformed(evt);
            }
        });
        mnuServices.add(mnuitemManageCashierAccounts);

        mnuitemViewProducts.setText("View Products");
        mnuitemViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemViewProductsActionPerformed(evt);
            }
        });
        mnuServices.add(mnuitemViewProducts);

        jMenuBar1.add(mnuServices);

        mnuExit.setText("Exit");

        mnuitemExit.setText("Close the Application");
        mnuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemExitActionPerformed(evt);
            }
        });
        mnuExit.add(mnuitemExit);

        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductSerialNumberActionPerformed

    private void mnuitemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemHomeActionPerformed

    private void mnuitemManageCashierAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemManageCashierAccountsActionPerformed
        // TODO add your handling code here:
        ManageCashierUI managecashierui = new ManageCashierUI();
        managecashierui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemManageCashierAccountsActionPerformed

    private void mnuitemViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemViewProductsActionPerformed
        // TODO add your handling code here:
        ProductUI productui = new ProductUI();
        productui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemViewProductsActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        if(checkValidation()) {
            String  productID = txtProductID.getText();
            String categoryID = String.valueOf(cmbCategoty.getSelectedItem());
            String productName = txtProductName.getText();
            int productPrice = Integer.valueOf(txtProductPrice.getText());
            String ProductSerialNumber = txtProductSerialNumber.getText();
            int productQuantity = Integer.valueOf(txtProductQuantity.getText());
        
            Products products = new Products(productID, categoryID, productName, productPrice, ProductSerialNumber, productQuantity);
        
//            String line = "ProductID : " + product.getProductID() + "\n " 
//                      + "CategoryID : "  + product.getCategoryID() + "\n" + " product Name : " 
//                      + product.getProductName() + "\n" + "Product Price : " + 
//                      product.getProductPrice() + "\n"  + "Serial Number : " +
//                      product.getProductSerialNumber() + "\n" +"Quantity : " + 
//                      product.getProductQuantity();
        
            boolean result = productsdb.add(products);
            if (result) {
                JOptionPane.showMessageDialog(this,"New Product is Added Successfully!!");
            } else {
                JOptionPane.showMessageDialog(this,"New Product isn't Added Successfully!!");
            }
//          System.out.println(line);
            
            // Clear the text fields
            txtProductID.setText("");
            cmbCategoty.setSelectedItem("Mac");
            txtProductName.setText("");
            txtProductPrice.setText("");
            txtProductSerialNumber.setText("");
            txtProductQuantity.setText("");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnViewallProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewallProductsActionPerformed
        // TODO add your handling code here:
        ArrayList<Products> productsList = productsdb.getAll();
            tblModel.setRowCount(0);
            for (Products products:productsList) {
                String  productID = products.getProductID();
                String categoryID = products.getCategoryID();
                String productName = products.getProductName();
                int productPrice = products.getProductPrice();
                String ProductSerialNumber = products.getProductSerialNumber();
                int productQuantity = products.getProductQuantity();
                tblModel.addRow(new Object[] {productID, categoryID, productName, productPrice , ProductSerialNumber , productQuantity});
            }
    }//GEN-LAST:event_btnViewallProductsActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        // TODO add your handling code here:
        String productID = JOptionPane.showInputDialog("Enter the Product ID");
        Products products = productsdb.get(productID);
        if (products != null) {
            txtProductID.setText(String.valueOf(products.getProductID()));
            cmbCategoty.setSelectedItem(products.getCategoryID());
            txtProductName.setText(products.getProductName());
            txtProductPrice.setText(String.valueOf(products.getProductPrice()));
            txtProductSerialNumber.setText(products.getProductSerialNumber());
            txtProductQuantity.setText(String.valueOf(products.getProductQuantity()));
        } else {
            JOptionPane.showMessageDialog(this, "The Record is not Found!!");
        }
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
        String productID = JOptionPane.showInputDialog("Enter the Product ID : ");
        boolean deleted = productsdb.delete(productID);
        if (deleted) {
            JOptionPane.showMessageDialog(this, "The Product is being Successfully Deleted!! ");
        } else {
            JOptionPane.showMessageDialog(this, "The Record is not Found!! ");
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnUpdateProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductsActionPerformed
        // TODO add your handling code here:
        if(checkValidation()) {
            String productID = txtProductID.getText();
            String categoryID = String.valueOf(cmbCategoty.getSelectedItem());
            String productName = txtProductName.getText();
            int productPrice = Integer.valueOf(txtProductPrice.getText());
            String ProductSerialNumber = txtProductSerialNumber.getText();
            int productQuantity = Integer.valueOf(txtProductQuantity.getText());
        
            Products products = new Products(productID, categoryID, productName, productPrice, ProductSerialNumber, productQuantity);
        
//            String line = "ProductID : " + product.getProductID() + "\n " 
//                      + "CategoryID : "  + product.getCategoryID() + "\n" + " product Name : " 
//                      + product.getProductName() + "\n" + "Product Price : " + 
//                      product.getProductPrice() + "\n"  + "Serial Number : " +
//                      product.getProductSerialNumber() + "\n" +"Quantity : " + 
//                      product.getProductQuantity();
        
            boolean result = productsdb.update(products);
            if (result) {
                JOptionPane.showMessageDialog(this,"Product is Updated Successfully!!");
            } else {
                JOptionPane.showMessageDialog(this,"Product isn't Updated Successfully!!");
            }
//          System.out.println(line);
            
            // Clear the text fields
            txtProductID.setText("");
            cmbCategoty.setSelectedItem("Mac");
            txtProductName.setText("");
            txtProductPrice.setText("");
            txtProductSerialNumber.setText("");
            txtProductQuantity.setText("");
        }
    }//GEN-LAST:event_btnUpdateProductsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManagerCockpitUI managercockpitui = new ManagerCockpitUI();
        managercockpitui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void mnuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProductsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProductsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProductsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProductsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProductsUI().setVisible(true);
            }
        });
    }

    private boolean checkValidation() {
        if (txtProductID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Product ID Cannot be Empty");
            return false;
        }
        if (txtProductName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Product Name Cannot be Empty");
            return false;
        }
        if (txtProductPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Product Price Cannot be Empty");
            return false;
        }
        try {
            int productPrice = Integer.valueOf(txtProductPrice.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Product Price Must Be Numeric!!");
            return false;
        }
        if (txtProductSerialNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Serial Number of the Product Cannot be Empty");
            return false;
        }
        if (txtProductQuantity.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Product Quantity Cannot be Empty");
            return false;
        }
        try {
            int productQuantity = Integer.valueOf(txtProductQuantity.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Product Quantity Must Be Numeric!!");
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnUpdateProducts;
    private javax.swing.JButton btnViewallProducts;
    private javax.swing.JComboBox<String> cmbCategoty;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddorEditProducts;
    private javax.swing.JLabel lblProductCategory;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblProductQuantity;
    private javax.swing.JLabel lblProductSerialNumber;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuServices;
    private javax.swing.JMenu mnuiStore;
    private javax.swing.JMenuItem mnuitemExit;
    private javax.swing.JMenuItem mnuitemHome;
    private javax.swing.JMenuItem mnuitemManageCashierAccounts;
    private javax.swing.JMenuItem mnuitemViewProducts;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JTextField txtProductSerialNumber;
    // End of variables declaration//GEN-END:variables
}
