/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import business.Cashier;
import data.CashierDB;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chand
 */
public class ManageCashierUI extends javax.swing.JFrame {

    private CashierDB cashierdb;
    private DefaultTableModel tblModel;
    
    /**
     * Creates new form ManageCashierUI
     */
    public ManageCashierUI() {
        initComponents();
        setLocationRelativeTo(this);
        cashierdb = new CashierDB();
        tblModel = new DefaultTableModel();
        tblCashier.setModel(tblModel);
        tblModel.addColumn("Cashier Username");
        tblModel.addColumn("Cashier Password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCashier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblCashierUsername = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCashierUsername = new javax.swing.JTextField();
        pswCashierPassword = new javax.swing.JPasswordField();
        btnAddCashier = new javax.swing.JButton();
        btnSearchCashier = new javax.swing.JButton();
        btnDeleteCashier = new javax.swing.JButton();
        btnViewallCashiers = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdateCashier = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuiStore = new javax.swing.JMenu();
        mnuitemHome = new javax.swing.JMenuItem();
        mnuManagerServices = new javax.swing.JMenu();
        mnuitemManageProducts = new javax.swing.JMenuItem();
        mnuViewProducts = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();
        mnuClosetheappication = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Cashier Accounts");
        setResizable(false);

        tblCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCashier);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Cashier Accounts");

        lblCashierUsername.setText("Cashier Username");

        jLabel5.setText("Cashier Password");

        btnAddCashier.setText("Add");
        btnAddCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCashierActionPerformed(evt);
            }
        });

        btnSearchCashier.setText("Search");
        btnSearchCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCashierActionPerformed(evt);
            }
        });

        btnDeleteCashier.setText("Delete");
        btnDeleteCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCashierActionPerformed(evt);
            }
        });

        btnViewallCashiers.setText("View All");
        btnViewallCashiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewallCashiersActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateCashier.setText("Update");
        btnUpdateCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCashierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnAddCashier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchCashier)
                                .addGap(34, 34, 34)
                                .addComponent(btnUpdateCashier)
                                .addGap(43, 43, 43)
                                .addComponent(btnDeleteCashier)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pswCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnViewallCashiers)
                                .addGap(42, 42, 42)
                                .addComponent(btnBack)
                                .addGap(29, 29, 29)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashierUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswCashierPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCashier)
                    .addComponent(btnSearchCashier)
                    .addComponent(btnDeleteCashier)
                    .addComponent(btnViewallCashiers)
                    .addComponent(btnBack)
                    .addComponent(btnUpdateCashier))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnuiStore.setText("iStore");
        mnuiStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiStoreActionPerformed(evt);
            }
        });

        mnuitemHome.setText("Home");
        mnuitemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemHomeActionPerformed(evt);
            }
        });
        mnuiStore.add(mnuitemHome);

        jMenuBar1.add(mnuiStore);

        mnuManagerServices.setText("Services");

        mnuitemManageProducts.setText("Manage Products");
        mnuitemManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemManageProductsActionPerformed(evt);
            }
        });
        mnuManagerServices.add(mnuitemManageProducts);

        mnuViewProducts.setText("View Products");
        mnuViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewProductsActionPerformed(evt);
            }
        });
        mnuManagerServices.add(mnuViewProducts);

        jMenuBar1.add(mnuManagerServices);

        mnuExit.setText("Exit");

        mnuClosetheappication.setText("Close the Application");
        mnuClosetheappication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClosetheappicationActionPerformed(evt);
            }
        });
        mnuExit.add(mnuClosetheappication);

        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiStoreActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuiStoreActionPerformed

    private void mnuitemManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemManageProductsActionPerformed
        // TODO add your handling code here:
        ManageProductsUI manageproductsui = new ManageProductsUI();
        manageproductsui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemManageProductsActionPerformed

    private void mnuViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewProductsActionPerformed
        // TODO add your handling code here:
        ProductUI productui = new ProductUI();
        productui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuViewProductsActionPerformed

    private void mnuClosetheappicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClosetheappicationActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuClosetheappicationActionPerformed

    private void mnuitemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemHomeActionPerformed

    private void btnAddCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCashierActionPerformed
        // TODO add your handling code here:
        if(checkValidation()) {
            String cashierUsername = txtCashierUsername.getText();
            String cashierPassword = pswCashierPassword.getText();
        
            Cashier cashier = new Cashier(cashierUsername, cashierPassword);
        
//            String line = "CashierID : " + cashier.getCashierID() + "\n" +
//                        "Cashier Name : " + cashier.getCashierName() + "\n" + 
//                        "Cashier Username : " + cashier.getCashierUsername() + "\n" + 
//                        "Cashier Password : " + cashier.getCashierPassword();
        
            boolean result = cashierdb.add(cashier);
            if (result) {
                JOptionPane.showMessageDialog(this,"New Cashier is Added Successfully!!");
            } else {
                JOptionPane.showMessageDialog(this,"New Cashier isn't Added Successfully!!");
            }
            txtCashierUsername.setText("");
            pswCashierPassword.setText("");
        }   
    }//GEN-LAST:event_btnAddCashierActionPerformed

    private void btnViewallCashiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewallCashiersActionPerformed
        // TODO add your handling code here:
        ArrayList<Cashier> cashierList = cashierdb.getAll();
        tblModel.setRowCount(0);
        for (Cashier cashier:cashierList) {
            String cashierUsername = cashier.getCashierUsername();
            String cashierPassword = cashier.getCashierPassword();
            tblModel.addRow(new Object[] {cashierUsername, cashierPassword });
        }
    }//GEN-LAST:event_btnViewallCashiersActionPerformed

    private void btnSearchCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCashierActionPerformed
        // TODO add your handling code here:
        String cashierUsername = JOptionPane.showInputDialog("Enter the Cashier ID : ");
        Cashier cashier = cashierdb.get(cashierUsername);
        if (cashier != null) {
            txtCashierUsername.setText(cashier.getCashierUsername());
            pswCashierPassword.setText(cashier.getCashierPassword());
        } else {
            JOptionPane.showMessageDialog(this, "The Record is not Found!!");
        }
    }//GEN-LAST:event_btnSearchCashierActionPerformed

    private void btnDeleteCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCashierActionPerformed
        // TODO add your handling code here:
        String cashierUsername = JOptionPane.showInputDialog("Enter the Cashier ID : ");
        boolean deleted = cashierdb.delete(cashierUsername);
        if (deleted){
            JOptionPane.showMessageDialog(this, "The Cashier is being Successfully Deleted!!");
        } else {
            JOptionPane.showMessageDialog(this, "The Record is not Found!!");
        }
    }//GEN-LAST:event_btnDeleteCashierActionPerformed

    private void btnUpdateCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCashierActionPerformed
        // TODO add your handling code here:
        if(checkValidation()) {
            String cashierUsername = txtCashierUsername.getText();
            String cashierPassword = pswCashierPassword.getText();
        
            Cashier cashier = new Cashier(cashierUsername, cashierPassword);
        
//            String line = "CashierID : " + cashier.getCashierID() + "\n" +
//                        "Cashier Name : " + cashier.getCashierName() + "\n" + 
//                        "Cashier Username : " + cashier.getCashierUsername() + "\n" + 
//                        "Cashier Password : " + cashier.getCashierPassword();
        
            boolean result = cashierdb.update(cashier);
            if (result) {
                JOptionPane.showMessageDialog(this,"Cashier is Updated Successfully!!");
            } else {
                JOptionPane.showMessageDialog(this,"Cashier isn't Updated Successfully!!");
            }
            txtCashierUsername.setText("");
            pswCashierPassword.setText("");
        }   
    }//GEN-LAST:event_btnUpdateCashierActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManagerCockpitUI managercockpitui = new ManagerCockpitUI();
        managercockpitui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCashierUI().setVisible(true);
            }
        });
    }

    private boolean checkValidation() {
        if (txtCashierUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cashier Username Cannot be Empty");
            return false;
        }
        if (pswCashierPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cashier Password Cannot be Empty");
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCashier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCashier;
    private javax.swing.JButton btnSearchCashier;
    private javax.swing.JButton btnUpdateCashier;
    private javax.swing.JButton btnViewallCashiers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCashierUsername;
    private javax.swing.JMenuItem mnuClosetheappication;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuManagerServices;
    private javax.swing.JMenuItem mnuViewProducts;
    private javax.swing.JMenu mnuiStore;
    private javax.swing.JMenuItem mnuitemHome;
    private javax.swing.JMenuItem mnuitemManageProducts;
    private javax.swing.JPasswordField pswCashierPassword;
    private javax.swing.JTable tblCashier;
    private javax.swing.JTextField txtCashierUsername;
    // End of variables declaration//GEN-END:variables
}
