/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

/**
 *
 * @author chand
 */
public class ManagerCockpitUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerCockpitUI
     */
    public ManagerCockpitUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblManagerCockpit = new javax.swing.JLabel();
        btnManageProducts = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnManageCashierAccounts = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuiStore = new javax.swing.JMenu();
        mnuitemHome = new javax.swing.JMenuItem();
        mnuServices = new javax.swing.JMenu();
        mnuitemManageCashierAccounts = new javax.swing.JMenuItem();
        mnuitemManageProducts = new javax.swing.JMenuItem();
        mnuitemViewProducts = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenu();
        mnuitemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager's Cockpit");
        setResizable(false);

        lblManagerCockpit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblManagerCockpit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagerCockpit.setText("Manager's Cockpit");

        btnManageProducts.setText("Manage Products");
        btnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductsActionPerformed(evt);
            }
        });

        jButton2.setText("View Products");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnManageCashierAccounts.setText("Manage Cashier Accounts");
        btnManageCashierAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCashierAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnManageCashierAccounts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblManagerCockpit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack)))))
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManagerCockpit)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCashierAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(28, 28, 28))
        );

        mnuiStore.setText("iStore");
        mnuiStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiStoreActionPerformed(evt);
            }
        });

        mnuitemHome.setText("Home");
        mnuitemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemHomeActionPerformed(evt);
            }
        });
        mnuiStore.add(mnuitemHome);

        jMenuBar1.add(mnuiStore);

        mnuServices.setText("Services");

        mnuitemManageCashierAccounts.setText("Manage Cashier Accounts");
        mnuitemManageCashierAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemManageCashierAccountsActionPerformed(evt);
            }
        });
        mnuServices.add(mnuitemManageCashierAccounts);

        mnuitemManageProducts.setText("Manage Products");
        mnuitemManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemManageProductsActionPerformed(evt);
            }
        });
        mnuServices.add(mnuitemManageProducts);

        mnuitemViewProducts.setText("View Products");
        mnuitemViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemViewProductsActionPerformed(evt);
            }
        });
        mnuServices.add(mnuitemViewProducts);

        jMenuBar1.add(mnuServices);

        mnuExit.setText("Exit");

        mnuitemExit.setText("Close the Application");
        mnuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemExitActionPerformed(evt);
            }
        });
        mnuExit.add(mnuitemExit);

        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void mnuiStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiStoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiStoreActionPerformed

    private void btnManageCashierAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCashierAccountsActionPerformed
        // TODO add your handling code here:
        ManageCashierUI managecashierui = new ManageCashierUI();
        managecashierui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnManageCashierAccountsActionPerformed

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        // TODO add your handling code here:
        ManageProductsUI manageproductsui = new ManageProductsUI();
        manageproductsui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ProductUI productsui = new ProductUI();
        productsui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnuitemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemHomeActionPerformed
        // TODO add your handling code here:
        HomeUI homeui = new HomeUI();
        homeui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemHomeActionPerformed

    private void mnuitemManageCashierAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemManageCashierAccountsActionPerformed
        // TODO add your handling code here:
        ManageCashierUI managecashierui = new ManageCashierUI();
        managecashierui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemManageCashierAccountsActionPerformed

    private void mnuitemManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemManageProductsActionPerformed
        // TODO add your handling code here:
        ManageProductsUI manageproductsui = new ManageProductsUI();
        manageproductsui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemManageProductsActionPerformed

    private void mnuitemViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemViewProductsActionPerformed
        // TODO add your handling code here:
        ProductUI productui = new ProductUI();
        productui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuitemViewProductsActionPerformed

    private void mnuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuitemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerCockpitUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerCockpitUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerCockpitUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerCockpitUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerCockpitUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageCashierAccounts;
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblManagerCockpit;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuServices;
    private javax.swing.JMenu mnuiStore;
    private javax.swing.JMenuItem mnuitemExit;
    private javax.swing.JMenuItem mnuitemHome;
    private javax.swing.JMenuItem mnuitemManageCashierAccounts;
    private javax.swing.JMenuItem mnuitemManageProducts;
    private javax.swing.JMenuItem mnuitemViewProducts;
    // End of variables declaration//GEN-END:variables
}
